# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kristinapultsina/flexbuild

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kristinapultsina/flexbuild

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kristinapultsina/flexbuild/CMakeFiles /Users/kristinapultsina/flexbuild/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kristinapultsina/flexbuild/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ship_chassis

# Build rule for target.
ship_chassis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ship_chassis
.PHONY : ship_chassis

# fast build rule for target.
ship_chassis/fast:
	$(MAKE) -f CMakeFiles/ship_chassis.dir/build.make CMakeFiles/ship_chassis.dir/build
.PHONY : ship_chassis/fast

#=============================================================================
# Target rules for targets named build_chassis

# Build rule for target.
build_chassis: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build_chassis
.PHONY : build_chassis

# fast build rule for target.
build_chassis/fast:
	$(MAKE) -f CMakeFiles/build_chassis.dir/build.make CMakeFiles/build_chassis.dir/build
.PHONY : build_chassis/fast

#=============================================================================
# Target rules for targets named unload_extr1

# Build rule for target.
unload_extr1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unload_extr1
.PHONY : unload_extr1

# fast build rule for target.
unload_extr1/fast:
	$(MAKE) -f CMakeFiles/unload_extr1.dir/build.make CMakeFiles/unload_extr1.dir/build
.PHONY : unload_extr1/fast

#=============================================================================
# Target rules for targets named unload_extr2

# Build rule for target.
unload_extr2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unload_extr2
.PHONY : unload_extr2

# fast build rule for target.
unload_extr2/fast:
	$(MAKE) -f CMakeFiles/unload_extr2.dir/build.make CMakeFiles/unload_extr2.dir/build
.PHONY : unload_extr2/fast

#=============================================================================
# Target rules for targets named load_parts

# Build rule for target.
load_parts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 load_parts
.PHONY : load_parts

# fast build rule for target.
load_parts/fast:
	$(MAKE) -f CMakeFiles/load_parts.dir/build.make CMakeFiles/load_parts.dir/build
.PHONY : load_parts/fast

#=============================================================================
# Target rules for targets named product

# Build rule for target.
product: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 product
.PHONY : product

# fast build rule for target.
product/fast:
	$(MAKE) -f CMakeFiles/product.dir/build.make CMakeFiles/product.dir/build
.PHONY : product/fast

#=============================================================================
# Target rules for targets named kin.robogripper

# Build rule for target.
kin.robogripper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kin.robogripper
.PHONY : kin.robogripper

# fast build rule for target.
kin.robogripper/fast:
	$(MAKE) -f CMakeFiles/kin.robogripper.dir/build.make CMakeFiles/kin.robogripper.dir/build
.PHONY : kin.robogripper/fast

#=============================================================================
# Target rules for targets named kin.manipulator

# Build rule for target.
kin.manipulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kin.manipulator
.PHONY : kin.manipulator

# fast build rule for target.
kin.manipulator/fast:
	$(MAKE) -f CMakeFiles/kin.manipulator.dir/build.make CMakeFiles/kin.manipulator.dir/build
.PHONY : kin.manipulator/fast

#=============================================================================
# Target rules for targets named agv.cart_in_cell

# Build rule for target.
agv.cart_in_cell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agv.cart_in_cell
.PHONY : agv.cart_in_cell

# fast build rule for target.
agv.cart_in_cell/fast:
	$(MAKE) -f CMakeFiles/agv.cart_in_cell.dir/build.make CMakeFiles/agv.cart_in_cell.dir/build
.PHONY : agv.cart_in_cell/fast

#=============================================================================
# Target rules for targets named cv.localize

# Build rule for target.
cv.localize: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv.localize
.PHONY : cv.localize

# fast build rule for target.
cv.localize/fast:
	$(MAKE) -f CMakeFiles/cv.localize.dir/build.make CMakeFiles/cv.localize.dir/build
.PHONY : cv.localize/fast

#=============================================================================
# Target rules for targets named cv.calibration

# Build rule for target.
cv.calibration: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv.calibration
.PHONY : cv.calibration

# fast build rule for target.
cv.calibration/fast:
	$(MAKE) -f CMakeFiles/cv.calibration.dir/build.make CMakeFiles/cv.calibration.dir/build
.PHONY : cv.calibration/fast

#=============================================================================
# Target rules for targets named parts_on_table

# Build rule for target.
parts_on_table: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 parts_on_table
.PHONY : parts_on_table

# fast build rule for target.
parts_on_table/fast:
	$(MAKE) -f CMakeFiles/parts_on_table.dir/build.make CMakeFiles/parts_on_table.dir/build
.PHONY : parts_on_table/fast

#=============================================================================
# Target rules for targets named kin.joinparts

# Build rule for target.
kin.joinparts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kin.joinparts
.PHONY : kin.joinparts

# fast build rule for target.
kin.joinparts/fast:
	$(MAKE) -f CMakeFiles/kin.joinparts.dir/build.make CMakeFiles/kin.joinparts.dir/build
.PHONY : kin.joinparts/fast

#=============================================================================
# Target rules for targets named kin.gripper

# Build rule for target.
kin.gripper: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kin.gripper
.PHONY : kin.gripper

# fast build rule for target.
kin.gripper/fast:
	$(MAKE) -f CMakeFiles/kin.gripper.dir/build.make CMakeFiles/kin.gripper.dir/build
.PHONY : kin.gripper/fast

#=============================================================================
# Target rules for targets named cv.camera1

# Build rule for target.
cv.camera1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv.camera1
.PHONY : cv.camera1

# fast build rule for target.
cv.camera1/fast:
	$(MAKE) -f CMakeFiles/cv.camera1.dir/build.make CMakeFiles/cv.camera1.dir/build
.PHONY : cv.camera1/fast

#=============================================================================
# Target rules for targets named kin.manipulator_released

# Build rule for target.
kin.manipulator_released: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kin.manipulator_released
.PHONY : kin.manipulator_released

# fast build rule for target.
kin.manipulator_released/fast:
	$(MAKE) -f CMakeFiles/kin.manipulator_released.dir/build.make CMakeFiles/kin.manipulator_released.dir/build
.PHONY : kin.manipulator_released/fast

#=============================================================================
# Target rules for targets named build_battarey

# Build rule for target.
build_battarey: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build_battarey
.PHONY : build_battarey

# fast build rule for target.
build_battarey/fast:
	$(MAKE) -f CMakeFiles/build_battarey.dir/build.make CMakeFiles/build_battarey.dir/build
.PHONY : build_battarey/fast

#=============================================================================
# Target rules for targets named cv.camera2

# Build rule for target.
cv.camera2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv.camera2
.PHONY : cv.camera2

# fast build rule for target.
cv.camera2/fast:
	$(MAKE) -f CMakeFiles/cv.camera2.dir/build.make CMakeFiles/cv.camera2.dir/build
.PHONY : cv.camera2/fast

#=============================================================================
# Target rules for targets named agv.cart_in_shipment

# Build rule for target.
agv.cart_in_shipment: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agv.cart_in_shipment
.PHONY : agv.cart_in_shipment

# fast build rule for target.
agv.cart_in_shipment/fast:
	$(MAKE) -f CMakeFiles/agv.cart_in_shipment.dir/build.make CMakeFiles/agv.cart_in_shipment.dir/build
.PHONY : agv.cart_in_shipment/fast

#=============================================================================
# Target rules for targets named agv.cart_in_warehouse

# Build rule for target.
agv.cart_in_warehouse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agv.cart_in_warehouse
.PHONY : agv.cart_in_warehouse

# fast build rule for target.
agv.cart_in_warehouse/fast:
	$(MAKE) -f CMakeFiles/agv.cart_in_warehouse.dir/build.make CMakeFiles/agv.cart_in_warehouse.dir/build
.PHONY : agv.cart_in_warehouse/fast

#=============================================================================
# Target rules for targets named cv.camera3

# Build rule for target.
cv.camera3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv.camera3
.PHONY : cv.camera3

# fast build rule for target.
cv.camera3/fast:
	$(MAKE) -f CMakeFiles/cv.camera3.dir/build.make CMakeFiles/cv.camera3.dir/build
.PHONY : cv.camera3/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... ship_chassis"
	@echo "... build_chassis"
	@echo "... unload_extr1"
	@echo "... rebuild_cache"
	@echo "... unload_extr2"
	@echo "... load_parts"
	@echo "... product"
	@echo "... kin.robogripper"
	@echo "... kin.manipulator"
	@echo "... agv.cart_in_cell"
	@echo "... cv.localize"
	@echo "... cv.calibration"
	@echo "... parts_on_table"
	@echo "... kin.joinparts"
	@echo "... kin.gripper"
	@echo "... cv.camera1"
	@echo "... kin.manipulator_released"
	@echo "... build_battarey"
	@echo "... cv.camera2"
	@echo "... agv.cart_in_shipment"
	@echo "... agv.cart_in_warehouse"
	@echo "... cv.camera3"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

